apiVersion: v1
kind: Pod
metadata:
    name: webapp-release0
    labels:
        app: webapp
        release: "0"
spec:
    containers:
    -   name: webapp-container01
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---
apiVersion: v1
kind: Pod
metadata:
    name: webapp-release0-5
    labels:
        app: webapp
        release: "0-5"
spec:
    containers:
    -   name: webapp-container01
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Pod
metadata:
    name: queue-release1
    labels:
        app: queue
        release: "1"
spec:
    containers:
    -   name: queue-container01
        image: richardchesterwood/k8s-fleetman-queue:release1
