apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: test-cron-job
spec:
    schedule: "* * * * *"
    jobTemplate:
        spec: # Job spec
            template:
                spec: # Pod spec
                    containers:
                    -   name: job-container
                        image: python:slim
                        command: ["python"]
                        args: ["-c", "import time; print('starting'); time.sleep(30); print('done')"]
                    restartPolicy: Never
            backoffLimit: 2