apiVersion: v1
kind: Pod
metadata:
    name: mysql
    labels:
        app: mysql
spec:
    containers:
    -   name: mysql
        image: mysql:5
        env:
        # Use secrets here actually
        -   name: MYSQL_ROOT_PASSWORD
            value: password
        -   name: MYSQL_DATABASE
            value: fleetman

---
apiVersion: v1
kind: Service
metadata:
    name: database
spec:
    selector:
        app: mysql
    type: ClusterIP
    ports:
    -   port: 3306
        # target ports are defaulted to ports, hence not specifying
