apiVersion: batch/v1
kind: Job
metadata:
    name: test-job
spec: # Job
    template:
        spec: # Pod
            containers:
            -   name: job-container
                image: python:slim
                command: ["python"]
                args: ["-c", "import time; print('starting'); time.sleep(30); print('done')"]
            restartPolicy: Never
    backoffLimit: 2