# Role defines a set of privileges for a type of user-role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: new-joiner-role
    namespace: default # Role-rules are always namespaced
rules:
-   apiGroups: ["", "apps", "autoscaling"] # Kubernetes API scope of rules - core and apps groups here
    resources: ["*"] # all resources (in the above namespace)
    verbs: ["get", "list", "watch"] # actions allowed for this role
    # verb names match the corresponding Kubernetes API requests

---
# RoleBinding allocates or "binds" users to Roles
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: new-joiner
    namespace: default
subjects:
    # list all of the users going into this role
-   kind: User
    name: anpalit
-   kind: User
    name: Ananya

roleRef:
    kind: Role
    name: new-joiner-role
    apiGroup: rbac.authorization.k8s.io
