# PVC defines what we want
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-pvc
spec:
    storageClassName: my-local-storage
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 20Gi

---
# PV defines how we implement a PVC
apiVersion: v1
kind: PersistentVolume
metadata:
    name: local-storage
spec:
    storageClassName: my-local-storage
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 20Gi
    hostPath:
        path: /mnt/mongodb-persistence
        type: DirectoryOrCreate
