apiVersion: v1
kind: ConfigMap
metadata:
    name: global-db-config-1
    namespace: default
data:
    database.url: "https://some-new-mysql-server.com:3306"
    database.password: "p@ssw0rd"

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: global-db-config-2
    namespace: default
data:
    database.url: "https://mysql.production.com:3306"
    database.password: "p@ssw0rd"
