# ClusterRole defines a set of privileges for a type of user-role cluster-wide
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: spring-role
rules:
-   apiGroups: [""] # Kubernetes API scope of rules
    resources: ["pods", "configmaps"] # all resources (in the above namespace)
    verbs: ["get", "list", "watch"] # actions allowed for this role
    # verb names match the corresponding Kubernetes API requests

---
# ClusterRoleBinding allocates or "binds" users to ClusterRoles
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: spring-ClusterRoleBinding
subjects:
    # list all of the users going into this role
-   kind: ServiceAccount
    name: default
    namespace: default

roleRef:
    kind: ClusterRole
    name: spring-role
    apiGroup: rbac.authorization.k8s.io
