apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: webapp
spec:
    selector:
        matchLabels:
            app: webapp
            release: "0-5"
    replicas: 2
    template:
        metadata:
            # pod name is not needed anymore, as the RS by its own will
            # name the pod - the RS' own name with a random string appended.
            #name: webapp-release0-5
            labels:
                app: webapp
                release: "0-5"
        spec:
            containers:
            -   name: webapp-container01
                image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Pod
metadata:
    name: queue-release1
    labels:
        app: queue
        release: "1"
spec:
    containers:
    -   name: queue-container01
        image: richardchesterwood/k8s-fleetman-queue:release1
